// Generated by van-stack/compiler. Do not edit by hand.

export const routes = [
  {
    id: "index",
    path: "/",
    files: {
      page: () => import("../src/routes/index/page.js"),
      meta: () => import("../src/routes/index/meta.js"),
    },
    layoutChain: [],
  },
  {
    id: "custom/[slug]",
    path: "/custom/:slug",
    files: {
      page: () => import("../src/routes/custom/[slug]/page.js"),
      loader: () => import("../src/routes/custom/[slug]/loader.js"),
      meta: () => import("../src/routes/custom/[slug]/meta.js"),
    },
    layoutChain: [() => import("../src/routes/custom/layout.js")],
  },
  {
    id: "hydrated/[slug]",
    path: "/hydrated/:slug",
    files: {
      page: () => import("../src/routes/hydrated/[slug]/page.js"),
      hydrate: () => import("../src/routes/hydrated/[slug]/hydrate.js"),
      loader: () => import("../src/routes/hydrated/[slug]/loader.js"),
      meta: () => import("../src/routes/hydrated/[slug]/meta.js"),
    },
    layoutChain: [() => import("../src/routes/hydrated/layout.js")],
  },
  {
    id: "shell/[slug]",
    path: "/shell/:slug",
    files: {
      page: () => import("../src/routes/shell/[slug]/page.js"),
      loader: () => import("../src/routes/shell/[slug]/loader.js"),
      meta: () => import("../src/routes/shell/[slug]/meta.js"),
    },
    layoutChain: [() => import("../src/routes/shell/layout.js")],
  },
] as const;

export default routes;
