import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";

import type { NormalizedRoute, RouteFileKind } from "../../core/src/index";

import { discoverRoutes } from "./discover-routes";
import { compileRoutesFromPaths } from "./fs-routes";

const routeFileOrder: RouteFileKind[] = [
  "page",
  "layout",
  "loader",
  "action",
  "entries",
  "meta",
  "error",
];

type BuildRouteManifestOptions = {
  root: string;
  outFile?: string;
  filePaths?: string[];
};

type LoadRoutesOptions = {
  root: string;
  filePaths?: string[];
};

export type RouteManifest = {
  routes: NormalizedRoute[];
  code: string;
  outFile: string;
};

export type RouteModuleLoader<T = unknown> = () => Promise<{ default: T }>;

export type LoadedRoute = {
  id: string;
  path: string;
  files: Partial<Record<RouteFileKind, RouteModuleLoader>>;
  layoutChain: RouteModuleLoader[];
};

function normalizePath(path: string): string {
  return path.split(sep).join("/");
}

function inferProjectRoot(routesRoot: string): string {
  const normalizedRoot = resolve(routesRoot);
  const parts = normalizedRoot.split(sep);

  if (parts.at(-1) === "routes" && parts.at(-2) === "src") {
    return dirname(dirname(normalizedRoot));
  }

  return dirname(normalizedRoot);
}

function inferOutFile(routesRoot: string, outFile?: string): string {
  if (outFile) return resolve(outFile);

  return join(
    inferProjectRoot(routesRoot),
    ".van-stack",
    "routes.generated.ts",
  );
}

function toImportPath(fromFile: string, toFile: string): string {
  const relativePath = normalizePath(
    relative(dirname(fromFile), resolve(toFile)),
  );
  return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
}

function renderImportFactory(targetFile: string, outFile: string): string {
  return `() => import("${toImportPath(outFile, targetFile)}")`;
}

function createModuleLoader(targetFile: string): RouteModuleLoader {
  const href = pathToFileURL(resolve(targetFile)).href;

  return () => import(/* @vite-ignore */ href);
}

function buildLoadedRoute(
  route: NormalizedRoute,
  routesRoot: string,
): LoadedRoute {
  const files: LoadedRoute["files"] = {};

  for (const key of routeFileOrder) {
    const filePath = route.files[key];
    if (!filePath) continue;

    files[key] = createModuleLoader(filePath);
  }

  return {
    id: route.id,
    path: route.path,
    files,
    layoutChain: route.layoutChain.map((segment) =>
      createModuleLoader(join(routesRoot, ...segment.split("/"), "layout.ts")),
    ),
  };
}

function renderFiles(route: NormalizedRoute, outFile: string): string[] {
  const keys = routeFileOrder.filter((key) => route.files[key]);

  if (keys.length === 0) return ["      files: {},"]; // defensive

  return [
    "      files: {",
    ...keys.map((key) => {
      const filePath = route.files[key];
      return `        ${key}: ${renderImportFactory(filePath as string, outFile)},`;
    }),
    "      },",
  ];
}

function renderLayoutChain(
  route: NormalizedRoute,
  routesRoot: string,
  outFile: string,
): string {
  if (route.layoutChain.length === 0) {
    return "      layoutChain: [],";
  }

  const items = route.layoutChain.map((segment) =>
    renderImportFactory(
      join(routesRoot, ...segment.split("/"), "layout.ts"),
      outFile,
    ),
  );

  return `      layoutChain: [${items.join(", ")}],`;
}

function renderManifestCode(
  routes: NormalizedRoute[],
  routesRoot: string,
  outFile: string,
): string {
  const lines = [
    "// Generated by van-stack/compiler. Do not edit by hand.",
    "",
    "export const routes = [",
  ];

  for (const route of routes) {
    lines.push("  {");
    lines.push(`    id: "${route.id}",`);
    lines.push(`    path: "${route.path}",`);
    lines.push(...renderFiles(route, outFile));
    lines.push(renderLayoutChain(route, routesRoot, outFile));
    lines.push("  },");
  }

  lines.push("] as const;");
  lines.push("");
  lines.push("export default routes;");

  return lines.join("\n");
}

export async function buildRouteManifest(
  options: BuildRouteManifestOptions,
): Promise<RouteManifest> {
  const routesRoot = resolve(options.root);
  const outFile = inferOutFile(routesRoot, options.outFile);
  const filePaths =
    options.filePaths ?? (await discoverRoutes({ root: routesRoot }));
  const routes = compileRoutesFromPaths(filePaths, { root: routesRoot });
  const code = renderManifestCode(routes, routesRoot, outFile);

  return {
    routes,
    code,
    outFile,
  };
}

export async function loadRoutes(
  options: LoadRoutesOptions,
): Promise<LoadedRoute[]> {
  const routesRoot = resolve(options.root);
  const filePaths =
    options.filePaths ?? (await discoverRoutes({ root: routesRoot }));
  const routes = compileRoutesFromPaths(filePaths, { root: routesRoot });

  return routes.map((route) => buildLoadedRoute(route, routesRoot));
}

export async function writeRouteManifest(
  options: BuildRouteManifestOptions,
): Promise<string> {
  const manifest = await buildRouteManifest(options);

  await mkdir(dirname(manifest.outFile), { recursive: true });
  await writeFile(manifest.outFile, manifest.code, "utf8");

  return manifest.outFile;
}
