// Generated by van-stack/compiler. Do not edit by hand.

export const routes = [
  {
    id: "gallery/chunked/index",
    path: "/gallery/chunked",
    chunked: false,
    files: {
      page: () => import("../src/routes/gallery/chunked/index/page.js"),
      loader: () => import("../src/routes/gallery/chunked/index/loader.js"),
      meta: () => import("../src/routes/gallery/chunked/index/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
  {
    id: "gallery/chunked/authors",
    path: "/gallery/chunked/authors",
    chunked: true,
    files: {
      page: () => import("../src/routes/gallery/chunked/authors/page.js"),
      loader: () => import("../src/routes/gallery/chunked/authors/loader.js"),
      meta: () => import("../src/routes/gallery/chunked/authors/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
  {
    id: "gallery/chunked/authors/[slug]",
    path: "/gallery/chunked/authors/:slug",
    chunked: true,
    files: {
      page: () =>
        import("../src/routes/gallery/chunked/authors/[slug]/page.js"),
      loader: () =>
        import("../src/routes/gallery/chunked/authors/[slug]/loader.js"),
      meta: () =>
        import("../src/routes/gallery/chunked/authors/[slug]/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
  {
    id: "gallery/chunked/categories",
    path: "/gallery/chunked/categories",
    chunked: true,
    files: {
      page: () => import("../src/routes/gallery/chunked/categories/page.js"),
      loader: () =>
        import("../src/routes/gallery/chunked/categories/loader.js"),
      meta: () => import("../src/routes/gallery/chunked/categories/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
  {
    id: "gallery/chunked/categories/[slug]",
    path: "/gallery/chunked/categories/:slug",
    chunked: true,
    files: {
      page: () =>
        import("../src/routes/gallery/chunked/categories/[slug]/page.js"),
      loader: () =>
        import("../src/routes/gallery/chunked/categories/[slug]/loader.js"),
      meta: () =>
        import("../src/routes/gallery/chunked/categories/[slug]/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
  {
    id: "gallery/chunked/posts",
    path: "/gallery/chunked/posts",
    chunked: true,
    files: {
      page: () => import("../src/routes/gallery/chunked/posts/page.js"),
      loader: () => import("../src/routes/gallery/chunked/posts/loader.js"),
      meta: () => import("../src/routes/gallery/chunked/posts/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
  {
    id: "gallery/chunked/posts/[slug]",
    path: "/gallery/chunked/posts/:slug",
    chunked: true,
    files: {
      page: () => import("../src/routes/gallery/chunked/posts/[slug]/page.js"),
      loader: () =>
        import("../src/routes/gallery/chunked/posts/[slug]/loader.js"),
      meta: () => import("../src/routes/gallery/chunked/posts/[slug]/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
  {
    id: "gallery/chunked/tags",
    path: "/gallery/chunked/tags",
    chunked: true,
    files: {
      page: () => import("../src/routes/gallery/chunked/tags/page.js"),
      loader: () => import("../src/routes/gallery/chunked/tags/loader.js"),
      meta: () => import("../src/routes/gallery/chunked/tags/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
  {
    id: "gallery/chunked/tags/[slug]",
    path: "/gallery/chunked/tags/:slug",
    chunked: true,
    files: {
      page: () => import("../src/routes/gallery/chunked/tags/[slug]/page.js"),
      loader: () =>
        import("../src/routes/gallery/chunked/tags/[slug]/loader.js"),
      meta: () => import("../src/routes/gallery/chunked/tags/[slug]/meta.js"),
    },
    layoutChain: [],
    slotOwnerLayout: undefined,
    slotOwnerLayoutIndex: undefined,
    slots: undefined,
  },
] as const;

export default routes;
